### ISSUE TITLE
VL-PLM + AggDet Pretraining Model

### ISSUE THREAD

**Issue by zhangyupeng123** [WarlockWendell/AggDet#1]
When will the VL-PLM + AggDet Pretraining Model be released?

**Comment by WarlockWendell** [comment]
You can download the pre-trained VL-PLM models [here](https://github.com/xiaofeng94/VL-PLM?tab=readme-ov-file#evaluation-with-pre-trained-models). Our method is training-free, so you can directly use the original weights. The code is similar to Detic or CoDet.

**Comment by zhangyupeng123** [comment]
@WarlockWendell Thanks for your answer~
